apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-container
          image: yadasa/yadeko:latest
          ports:
            - containerPort: 3000 # Port your Node.js app is listening on

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80 # Expose your service on port 80 externally
      targetPort: 3000 # Port your Node.js app is listening on within the pod
  type: NodePort # Expose the service on a static port on each node
