apiVersion: apps/v1
kind: Deployment
metadata:
  name: newapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newapp
  template:
    metadata:
      labels:
        app: newapp
    spec:
      containers:
        - name: newapp-container
          image: yadasa/newapp
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: newapp-service
spec:
  selector:
    app: newapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
