apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv1-deployment
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: appv1
  template:
    metadata:
      labels:
        app: appv1
    spec:
      containers:
        - name: appv1-container
          image: yadasa/appv1:latest
          ports:
            - containerPort: 3000 # Port your Node.js app is listening on

---
apiVersion: v1
kind: Service
metadata:
  name: appv1-service
spec:
  selector:
    app: appv1
  ports:
    - protocol: TCP
      port: 80 # Expose your service on port 80 externally
      targetPort: 3000 # Port your Node.js app is listening on within the pod
  type: NodePort # Expose the service on a static port on each node
